// Base API URL
const BASE_URL = "http://localhost:5001/fuze-be491/us-central1/v1";

// Page templates
const pages = {
  analytics: `
    <div class="flex justify-between items-center mb-6 hidden md:flex">
      <h1 class="text-3xl font-bold text-amber-700">Event Analytics Dashboard</h1>
    </div>
    <div id="overview" class="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
      <div class="bg-white p-4 rounded shadow text-center">
        <h3 class="text-gray-500 text-sm mb-1">Countries</h3>
        <p id="totalCountries" class="text-2xl font-semibold">0</p>
      </div>
      <div class="bg-white p-4 rounded shadow text-center">
        <h3 class="text-gray-500 text-sm mb-1">Users</h3>
        <p id="totalUsers" class="text-2xl font-semibold">0</p>
      </div>
      <div class="bg-white p-4 rounded shadow text-center">
        <h3 class="text-gray-500 text-sm mb-1">Events</h3>
        <p id="totalEvents" class="text-2xl font-semibold">0</p>
      </div>
      <div class="bg-white p-4 rounded shadow text-center">
        <h3 class="text-gray-500 text-sm mb-1">Invited</h3>
        <p id="totalInvited" class="text-2xl font-semibold">0</p>
      </div>
    </div>
    <div class="grid md:grid-cols-2 gap-6">
      <div class="bg-white p-6 rounded shadow">
        <h2 class="text-lg font-semibold mb-3 text-center">Invited vs Not Invited</h2>
        <canvas id="invitedPieChart"></canvas>
      </div>
      <div class="bg-white p-6 rounded shadow">
        <h2 class="text-lg font-semibold mb-3 text-center">Users & Events by Country</h2>
        <canvas id="countryBarChart"></canvas>
      </div>
    </div>
  `,
  manage_event: null, // dynamic: generated by manageEvents.js
  users: `
    <h2 class="text-2xl font-bold text-amber-700 mb-4">Users</h2>
    <div id="usersContent">Select a country in "Manage Events" to load users.</div>
  `
};

// ---------------- Render Page ----------------
function renderPage(name) {
  const container = document.getElementById("page-container");

  switch(name) {
    case "analytics":
      container.innerHTML = pages.analytics;
      loadOverview();
      loadCharts();
      break;

    case "manage_event":
      initManageEvents(); // dynamic
      break;

    case "users":
      container.innerHTML = pages.users;
      break;

    default:
      container.innerHTML = "<h2>Page not found</h2>";
  }
}

// ---------------- Sidebar Navigation ----------------
document.querySelectorAll("aside nav button").forEach(btn => {
  btn.addEventListener("click", () => {
    renderPage(btn.dataset.page);
  });
});
